// Generated by Data Class Generator

using System;
using System.Collections.Generic;
using Proto.Enums;
using UnityEngine;

namespace Proto.Data
{
    [Serializable]
    public class TaskInfo
    {
        public int ID;
        public int Group;
        public string TaskType;
        public string Hint;
        public int ValueInt;
        public string ValueStr;
        public string SoundStop;
        public string NextTaskTrigger;
        public string EndActions;
    }

}

